INSERT INTO TB_RESKILL_AREA_INTERESSE (nome) VALUES ('TI & Desenvolvimento');
INSERT INTO TB_RESKILL_AREA_INTERESSE (nome) VALUES ('Marketing Digital');
INSERT INTO TB_RESKILL_AREA_INTERESSE (nome) VALUES ('Saúde e Bem-estar');
INSERT INTO TB_RESKILL_AREA_INTERESSE (nome) VALUES ('Gestão e Negócios');
INSERT INTO TB_RESKILL_AREA_INTERESSE (nome) VALUES ('Design e UX');